# Form implementation generated from reading ui file 'videoprocess.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets, QtGui
from PyQt6.QtGui import QAction
from PyQt6.QtWidgets import QMenuBar, QMenu, QWidget, QMainWindow


class Ui_VideoProcess(object):

    def __init__(self):
        super().__init__()

    def setupUi(self, VideoProcess):
        VideoProcess.setObjectName("VideoProcess")
        VideoProcess.resize(791, 565)
        self.horizontalLayoutWidget = QtWidgets.QWidget(VideoProcess)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(410, 0, 371, 76))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.img_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.img_button.setObjectName("img_button")
        self.horizontalLayout.addWidget(self.img_button)
        self.exit_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.exit_button.setObjectName("exit_button")
        self.horizontalLayout.addWidget(self.exit_button)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(VideoProcess)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, -20, 261, 80))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.file_button = QtWidgets.QToolButton(self.horizontalLayoutWidget_2)
        self.file_button.setPopupMode(QtWidgets.QToolButton.ToolButtonPopupMode.InstantPopup)
        self.file_button.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextBesideIcon)
        self.file_button.setAutoRaise(True)
        self.file_button.setArrowType(QtCore.Qt.ArrowType.DownArrow)
        self.file_button.setObjectName("file_button")
        self.horizontalLayout_2.addWidget(self.file_button)
        self.func_button = QtWidgets.QToolButton(self.horizontalLayoutWidget_2)
        self.func_button.setPopupMode(QtWidgets.QToolButton.ToolButtonPopupMode.InstantPopup)
        self.func_button.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextBesideIcon)
        self.func_button.setAutoRaise(True)
        self.func_button.setArrowType(QtCore.Qt.ArrowType.DownArrow)
        self.func_button.setObjectName("func_button")
        self.horizontalLayout_2.addWidget(self.func_button)
        self.info_button = QtWidgets.QToolButton(self.horizontalLayoutWidget_2)
        self.info_button.setPopupMode(QtWidgets.QToolButton.ToolButtonPopupMode.InstantPopup)
        self.info_button.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextBesideIcon)
        self.info_button.setAutoRaise(True)
        self.info_button.setArrowType(QtCore.Qt.ArrowType.DownArrow)
        self.info_button.setObjectName("info_button")
        self.horizontalLayout_2.addWidget(self.info_button)
        self.img_label = QtWidgets.QLabel(VideoProcess)
        self.img_label.setGeometry(QtCore.QRect(50, 70, 591, 421))
        self.img_label.setText("")
        self.img_label.setObjectName("img_label")
        self.verticalLayoutWidget = QtWidgets.QWidget(VideoProcess)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(660, 80, 121, 381))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.model0_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.model0_button.setObjectName("model0_button")
        self.verticalLayout.addWidget(self.model0_button)
        self.model1_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.model1_button.setObjectName("model1_button")
        self.verticalLayout.addWidget(self.model1_button)
        self.model2_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.model2_button.setObjectName("model2_button")
        self.verticalLayout.addWidget(self.model2_button)
        self.mode3_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.mode3_button.setObjectName("mode3_button")
        self.verticalLayout.addWidget(self.mode3_button)
        self.model4_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.model4_button.setObjectName("model4_button")
        self.verticalLayout.addWidget(self.model4_button)

        #menu
        self.menubar = QMenuBar()
        self.file_menu = self.menubar.addMenu('文件')
        self.menuItem1 = QAction('保存当前帧', self)
        self.file_menu.addAction(self.menuItem1)
        self.verticalLayout.setMenuBar(self.menubar)
        self.file_button.setMenu(self.file_menu)

        self.menubar2 = QMenuBar()
        self.func_menu = self.menubar.addMenu('功能')
        self.menuItem2 = QAction('中英文转换',self)
        self.func_menu.addAction(self.menuItem2)
        self.verticalLayout.setMenuBar(self.menubar)
        self.func_button.setMenu(self.func_menu)

        self.menubar3 = QMenuBar()
        self.info_menu = self.menubar.addMenu('功能')
        self.menuItem3 = QAction('有关信息', self)
        self.info_menu.addAction(self.menuItem3)
        self.verticalLayout.setMenuBar(self.menubar)
        self.info_button.setMenu(self.info_menu)



        self.retranslateUi(VideoProcess)
        self.exit_button.clicked.connect(lambda: VideoProcess.close())  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(VideoProcess)

    def retranslateUi(self, VideoProcess):
        _translate = QtCore.QCoreApplication.translate
        VideoProcess.setWindowTitle(_translate("VideoProcess", "由刘滨榕开发的摄像头画面处理功能"))
        self.img_button.setText(_translate("VideoProcess", "图片处理"))
        self.exit_button.setText(_translate("VideoProcess", "退出"))
        self.file_button.setText(_translate("VideoProcess", "文件"))
        self.func_button.setText(_translate("VideoProcess", "功能"))
        self.info_button.setText(_translate("VideoProcess", "信息"))
        self.model0_button.setText(_translate("VideoProcess", "原始摄像头"))
        self.model1_button.setText(_translate("VideoProcess", "启用边缘检测"))
        self.model2_button.setText(_translate("VideoProcess", "启用二值化"))
        self.mode3_button.setText(_translate("VideoProcess", "启用灰度化"))
        self.model4_button.setText(_translate("VideoProcess", "启用硬币检测"))
